#Jekyll
name: www.RyanHornberger.com
url: http://www.ryanhornberger.com
copyright: RyanHornberger.com 2014
source: src
destination: dist
permalink: /:categories/:year/:title/

#pygments: true

markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

sass:
  sass_dir: a

sitemap:
    filename: "/sitemap.xml"
    exclude:
      - "/research"
      - "/a"