#Jekyll
name: www.RyanHornberger.com
pygments: true
source: src
destination: dist
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md','*.iml']

markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

#IXT Asset Compilations
assets:
  js_compressor: yui
  css_compressor: sass
  cachebust: soft
