#Jekyll
name: www.RyanHornberger.com
source: src
destination: dist
permalink: /articles/:title
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md','*.iml']

#pygments: true

markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

sass:
    sass_dir: -assets
