#Jekyll
name: www.RyanHornberger.com
pygments: true
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md','*.iml']

#IXT Asset Compilations
assets:
  js_compressor: yui
  css_compressor: sass
  cachebust: soft
